from .role import Role
from .user import User
from .course import Course
from .university import University
from .todo import Todo
from .applications import Applications
from .application_period import ApplicationPeriod
from .faq import Faq 
from .deadlines import Deadlines